services:
  configurator:
    environment:
      # This points to your specific repo
      PROJECT_CLONE_URL: https://github.com/WillzWayn/ml-bootcamp-lab

  workspace:
    # We use the Python workspace image for ML tasks
    image: dockersamples/labspace-workspace-python
    
    ports: !override
      - "8080:8080" # Port for any web apps (like Streamlit or FastAPI)
      - "8888:8888" # Port for Jupyter Lab (if used)

    environment:
      DANGEROUSLY_OMIT_AUTH: "true"
